version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo yum update -y || (echo "Failed to update packages" && exit 1)
      - sudo yum install nginx -y || (echo "Failed to install NGINX" && exit 1)
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - "**/*"
